# Generated by Django 2.1.5 on 2019-01-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20190125_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABL_UPLOAD_DATA_DISTRIBUTORINFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strBasicDate', models.CharField(max_length=10)),
                ('strClassFundCode', models.CharField(blank=True, max_length=10, null=True)),
                ('strSellerCode', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ABL_UPLOAD_DATA_FUNDPRICE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strBasicDate', models.CharField(max_length=10)),
                ('strClassFundCode', models.CharField(max_length=10)),
                ('strModifyBasicPrice', models.CharField(max_length=10, null=True)),
                ('strBasicPriceDayVariation', models.CharField(max_length=10, null=True)),
                ('strBasicTablePrice', models.CharField(max_length=10, null=True)),
                ('strBasicTablePriceDayVariation', models.CharField(max_length=10, null=True)),
                ('strAssetTotal', models.CharField(max_length=10, null=True)),
                ('strSetAccount', models.CharField(max_length=10, null=True)),
                ('strBasicPrice', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
