# Generated by Django 2.1.5 on 2019-01-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_abl_upload_data_distributorinfo_abl_upload_data_fundprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABL_UPLOAD_DATA_FUNDPERFORMANCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strBasicDate', models.CharField(max_length=10)),
                ('strClassFundCode', models.CharField(max_length=10)),
                ('strStock', models.CharField(max_length=10, null=True)),
                ('strBond', models.CharField(max_length=10, null=True)),
                ('strBeneficiaryCertificate', models.CharField(max_length=10, null=True)),
                ('stShortTerm', models.CharField(max_length=10, null=True)),
                ('strPF1D', models.CharField(max_length=10, null=True)),
                ('strBM1D', models.CharField(max_length=10, null=True)),
                ('strPF1M', models.CharField(max_length=10, null=True)),
                ('strBM1M', models.CharField(max_length=10, null=True)),
                ('strPF3M', models.CharField(max_length=10, null=True)),
                ('strBM3M', models.CharField(max_length=10, null=True)),
                ('strPF6M', models.CharField(max_length=10, null=True)),
                ('strBM6M', models.CharField(max_length=10, null=True)),
                ('strPF1Y', models.CharField(max_length=10, null=True)),
                ('strBM1Y', models.CharField(max_length=10, null=True)),
                ('strPF2Y', models.CharField(max_length=10, null=True)),
                ('strBM2Y', models.CharField(max_length=10, null=True)),
                ('strPF3Y', models.CharField(max_length=10, null=True)),
                ('strBM3Y', models.CharField(max_length=10, null=True)),
                ('strPF5Y', models.CharField(max_length=10, null=True)),
                ('strBM5Y', models.CharField(max_length=10, null=True)),
                ('strPFYTD', models.CharField(max_length=10, null=True)),
                ('strBMYTD', models.CharField(max_length=10, null=True)),
                ('strPFSINCE', models.CharField(max_length=10, null=True)),
                ('strBMSINCE', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ABL_UPLOAD_DATA_HOLDINGTOP5SECTOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strBasicDate', models.CharField(max_length=10)),
                ('strClassFundCode', models.CharField(max_length=10)),
                ('strSectorType', models.CharField(max_length=10)),
                ('StrOrder', models.CharField(max_length=10)),
                ('strSectorNAme', models.CharField(max_length=100, null=True)),
                ('strImportance', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ABL_UPLOAD_DATA_RISKANALYSIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strBasicDate', models.CharField(max_length=10)),
                ('strClassFundCode', models.CharField(max_length=10)),
                ('strMonthBase', models.CharField(max_length=10, null=True)),
                ('strStandardDeviation', models.CharField(max_length=10, null=True)),
                ('strMarketSensitive', models.CharField(max_length=10, null=True)),
                ('strSharpRatio', models.CharField(max_length=10, null=True)),
                ('strIR', models.CharField(max_length=10, null=True)),
                ('strStandardDeviation2', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
